require:
  - rubocop

AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable
  inherit_mode: merge
  Exclude:
   - 'bin/bundle'
   - app/controllers/differences_controller.rb

Style/Documentation:
  Enabled: false